name: Dev - API Server CI/CD

on:
  pull_request_target:
    branches: [ "dev" ]
    types: 
      - opened
      - synchronize
      - closed
      - labeled

jobs:
  # safe tagÏóê ÎåÄÌïú gradlew test && mergedÏóê ÎåÄÌïú gradlew build/deploy
  CI:
    if: contains(github.event.pull_request.labels.*.name, 'safe to api server üöÄ')
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Cache Gradle
    - name: Cache Gradle
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    ### runner application java ÏÑ§Ï†ï
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    ### application.yml ÏÑ§Ï†ï  
    - name: Set YML
      run: |
        echo "${{ secrets.APPLICATION_DEV_YML }}" | base64 --decode > ./Dev/API-Server/src/main/resources/application-dev.yml

    ### gradlew Ïã§Ìñâ Í∂åÌïú Î∂ÄÏó¨
    - name: Grant execute permisstion for gradlew
      run: |
        cd ./Dev/API-Server
        chmod +x gradlew

    ### project build
    - name: Build with Gradle
      run: |
        cd ./Dev/API-Server
        ./gradlew clean build -x test

    ### Docker Image Build and Push
    - name: Login to Docker Hub
      if: github.event.pull_request.merged == true
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      if: github.event.pull_request.merged == true
      uses: docker/setup-buildx-action@v2

    - name: Build and push
      if: github.event.pull_request.merged == true
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dev/API-Server/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPONAME }}

  # closedÏóê ÎåÄÌïú server deploy
  CD:
    if: github.event.pull_request.merged == true
    needs: [CI]

    runs-on: ubuntu-20.04

    steps:
    ### SSH Connect and Docker Image Pull and Container Run
    - name: Docker Image Pull and Container Run
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.DEV_SSH_HOST }}
        username: ${{ secrets.DEV_SSH_USERNAME }}
        password: ${{ secrets.DEV_SSH_PASSWORD }}
        key: ${{ secrets.DEV_SSH_KEY }}
        port: ${{ secrets.DEV_SSH_PORT }}
        script: |
          docker stop was
          docker rm was
          docker image rm ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPONAME }}
          docker run -d -p 8080:8080 -v /etc/localtime:/etc/localtime:ro -e TZ=Asia/Seoul --name was ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPONAME }}
